# Generated by Django 4.0.4 on 2023-03-09 12:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Enter First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Enter Last Name')),
                ('age', models.CharField(max_length=200, verbose_name='Enter Age of Missing Person')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, verbose_name='Select Gender of Missing Person')),
                ('last_seen', models.CharField(max_length=200, verbose_name='The Last Seen Location')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Provide Any Relevant Details')),
                ('photo', models.ImageField(upload_to='missingpersons/', verbose_name='Upload Photo of Missing Person')),
                ('reported_photo', models.ImageField(upload_to='reportedfoundpersons/', verbose_name='Reported Photo of Missing Person found')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Person to be Contacted')),
                ('contact_relationship', models.CharField(choices=[('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Father', 'Father'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Relative', 'Relative'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=200, verbose_name='Select Relationship with the Missing Person')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number')),
                ('status', models.CharField(choices=[('New', 'New'), ('Leads', 'Leads'), ('Found', 'Found'), ('Closed', 'Closed')], max_length=200, verbose_name='Current Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Person Background Check Done?')),
                ('face_encoding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Face Encoding of Missing Person')),
                ('is_matched_with_missing_person', models.BooleanField(default=False, verbose_name='Has the Match been Found?')),
                ('found_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Found Location')),
                ('found_time', models.DateTimeField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Has Contact Person Been Informed?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing People',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='ReportedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_location', models.CharField(max_length=200, verbose_name='Found Location')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Any Other Relevant Details')),
                ('photo', models.ImageField(upload_to='reportedpersons/', verbose_name='Upload Photo of Reported Person')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is this valid reporting?')),
                ('face_encoding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Face Encoding of Reported Person')),
                ('is_matched_with_missing_person', models.BooleanField(default=False, verbose_name='Has the Match been Found?')),
                ('matched_confidence', models.CharField(blank=True, max_length=200, null=True, verbose_name='Details of the Match')),
                ('matched_face_encoding', models.CharField(blank=True, max_length=200, null=True, verbose_name='Face Encoding of Matched Person')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reported Person',
                'verbose_name_plural': 'Reported Persons',
                'ordering': ('created_date',),
            },
        ),
    ]
